package io.github.matosoe.controlehoras.ui.goals;

import android.app.Application; import androidx.annotation.NonNull; import androidx.lifecycle.AndroidViewModel; import androidx.lifecycle.LiveData; import androidx.lifecycle.MutableLiveData;
import java.time.*; import java.util.*;
import io.github.matosoe.controlehoras.data.local.AppDatabase; import io.github.matosoe.controlehoras.data.local.entity.*; import io.github.matosoe.controlehoras.data.repository.*; import io.github.matosoe.controlehoras.domain.model.GoalResult; import io.github.matosoe.controlehoras.domain.service.*;

public final class GoalsViewModel extends AndroidViewModel {
 public static final int DAY=0,WEEK=1,CUSTOM=2; private final MutableLiveData<GoalsState> state=new MutableLiveData<>(); private final CategoryRepository categories; private final TimeEntryRepository entries; private final ZoneId zone=ZoneId.systemDefault(); private final GoalCalculator calculator=new GoalCalculator(); private final PeriodAggregator aggregator=new PeriodAggregator(); private LocalDate start=LocalDate.now(),end=LocalDate.now().plusDays(1); private int mode=DAY;
 public GoalsViewModel(@NonNull Application app){super(app);AppDatabase db=AppDatabase.getInstance(app);categories=new CategoryRepository(db);entries=new TimeEntryRepository(db);load();}
 @NonNull public LiveData<GoalsState> state(){return state;} public int mode(){return mode;}
 public void setMode(int value){mode=value; LocalDate today=LocalDate.now();if(value==DAY){start=today;end=today.plusDays(1);}else if(value==WEEK){start=today.minusDays(today.getDayOfWeek().getValue()%7);end=start.plusDays(7);}load();}
 public void setCustom(@NonNull LocalDate from,@NonNull LocalDate through){mode=CUSTOM;start=from;end=through.plusDays(1);load();}
 public void update(@NonNull CategoryEntity c,@NonNull RepositoryCallback<Integer> callback){categories.update(c,callback);}
 private void load(){final LocalDate requestedStart=start,requestedEnd=end;state.setValue(new GoalsState(start,end,Collections.emptyList(),0,0,0,true));long a=start.atStartOfDay(zone).toInstant().toEpochMilli(),b=end.atStartOfDay(zone).toInstant().toEpochMilli();categories.getAllOrdered(new RepositoryCallback<List<CategoryEntity>>(){public void onSuccess(List<CategoryEntity> cats){entries.getForPeriod(a,b,null,new RepositoryCallback<List<TimeEntryEntity>>(){public void onSuccess(List<TimeEntryEntity> values){if(!requestedStart.equals(start)||!requestedEnd.equals(end))return;Map<Long,Long> actual=aggregator.byCategory(values,a,b);long seconds=(b-a)/1000L,registered=actual.values().stream().mapToLong(Long::longValue).sum();List<GoalRow> rows=new ArrayList<>();int total=0;DurationFormatter f=new DurationFormatter();for(CategoryEntity c:cats){GoalResult r=calculator.calculate(actual.getOrDefault(c.id,0L),seconds,c.targetBasisPoints,c.goalType);total+=c.targetBasisPoints;String detail="Meta "+f.hhMm(Math.round(r.targetSeconds))+" ("+percent(c.targetBasisPoints/100.0)+") · Realizado "+f.hhMm(r.actualSeconds)+" ("+percent(r.actualPercent)+") · Desvio "+signed(f.hhMm(Math.round(Math.abs(r.deviationSeconds))),r.deviationSeconds)+" · "+(r.achieved?"Atingida":"Não atingida");rows.add(new GoalRow(c,detail));}state.postValue(new GoalsState(requestedStart,requestedEnd,rows,registered,Math.max(0,seconds-registered),total,false));}public void onError(Throwable e){}});}public void onError(Throwable e){}});}
 private static String percent(double value){return String.format(Locale.getDefault(),"%.1f%%",value);} private static String signed(String value,double n){return (n>=0?"+":"-")+value;}
}
